### ISSUE TITLE
ImportError: No module named 'crosspm'

### ISSUE THREAD

**Issue by vpag** [devopshq/crosspm#23]
Found in ff4ad02.

```
> py cpm.py

Traceback (most recent call last):
  File "cpm.py", line 31, in <module>
    import crosspm
ImportError: No module named 'crosspm'
```

Hint: cpm.py module is located just under crosspm directory. Please move it one level up, or fix imports.

**Comment by iaroslavscript** [comment]
usage:
```console
$ python -m crosspm.cpm
```
I don't know how to make it work as module and as callable script at the same time.
Any help would be much appreciated.

By the way there is a task #3 with suggestion rename cpm.py to main.py. So very soon it will look like this:
```console
$ python -m crosspm
```

**Comment by alkovpro** [comment]
Resolved long time ago :)
