### ISSUE TITLE
Unable to require particular pkg version

### ISSUE THREAD

**Issue by vpag** [devopshq/crosspm#24]
Found in ff4ad02.

`dependencies.txt` entry without wildcards in `version` like this
```
package  1.2.3  master
```
always causes
```
Error: pattern [1.2.3] does not match any version of package [package] for branch [master]
```
even though this version exists.

**Comment by iaroslavscript** [comment]
True for x.x.x version pattern.
Mark as critical

**Comment by iaroslavscript** [comment]
fixed with https://github.com/devopshq/crosspm/pull/25
