### ISSUE TITLE
Документация похоже устарела

### ISSUE THREAD

**Issue by TomskDiver** [devopshq/crosspm#43]
Заметил что на данный момент имеются различия в документации и README.
Например нет такого примера запуска:
> crosspm lock [DEPS] [DEPSLOCK] [options]

**Comment by Tim55667757** [comment]
Проблемы с разными версиями документации частично решаются в ветке https://github.com/devopshq/crosspm/tree/improve_ci

В частности, мы откажемся от read-the-docs сервиса и будем поддерживать актуальные версии документации только в gitlab-pages сервисе (в README.md).

После мержа указанной вестки README.md файл будем поддерживать в актуальном состоянии.

**Comment by Tim55667757** [comment]
@alkovpro Задачу можно закрывать после влития реквеста:
https://github.com/devopshq/crosspm/pull/47

Только перед этим проверь, пожалуйста, что пример выше - про лок - добавлен.

**Comment by Tim55667757** [comment]
В мастере документация наиболее актуальная на данный момент.

**Comment by TomskDiver** [comment]
@Tim55667757 прошу переоткрыть issue. Примера про crosspm lock так и нет. Т.е. документация не соответствует действительности.

**Comment by Tim55667757** [comment]
А, точно, я увидел crosspm lock [DEPS] [DEPSLOCK] [options] в #47 и не увидел пример на него, да. Прошу прощения, поспешил.

**Comment by allburov** [comment]
http://devopshq.github.io/crosspm/usage/USAGE#crosspm-lock
